-- CREATE TABLE
CREATE TABLE COINDESK(
  CREATE_TIME VARCHAR(255),
  UPDATE_TIME VARCHAR(255),
  CODE  VARCHAR(255) PRIMARY KEY,
  SYMBOL VARCHAR(255),
  RATE VARCHAR(255),
  DESCRIPTION VARCHAR(255),
  RATE_FLOAT DOUBLE
);

-- change PASSWORD
ALTER USER sa SET 666777